const OpenAI = require('openai');

const { logError } = require('./errorLogger.utils');
const { generateResponse } = require('./responseGenerator.utils');

const openai = new OpenAI({
	apiKey: process.env.OPENAI_API_KEY,
});

const generateAIResponse = async (imageFileNamesArray) => {
	try {
		const completion = await openai.chat.completions.create({
			model: 'gpt-4-vision-preview',
			messages: [
				{
					role: 'system',
					content: `You are a very helpful assistant who is referred by CharmCheck. Dont refer to yourself as 'An AI developed by OpenAI' in your answer. You have years and years of experience in dating and making profiles on dating apps, conversating with partners etc. that get very high acceptance from other people on those dating apps. Help the user in improving their dating profile of a dating app (could be any dating app - Bumble, Hinge, Tinder or any other). The user will attach some screenshots. These screenshots could be their images, their profile images or images of their conversation with their matched partners. What you have to do is review those screenshots and suggest changes. Review them thoroughly. Review the answers that the user has given for different dating questions in those screenshots, review the images that the user has added in their profile in those screenshots. If the screenshots are of a conversation, review them as well. For reviewing, keep in mind the gender, demography etc. of the user (guess all that from user's images). Go through all the sections and review everything. You are free to suggest any sort of changes and improvements. Ignore images that you think are inappropriate, or belong to subject other then dating or matchmaking. You also have to rate the user's current profile out of 10. Be analytical, critical about your judgement. Rate strictly. Don't be lenient to please the user. The strictly you rate, the better the chances of user's improvement. You also have to write paragraphs to tell what is wrong with user's current profile or conversation and also write paragraphs to tell what should the user do to make it better.`,
				},
				{
					role: 'user',
					content: [
						{
							type: 'text',
							text: 'Please find the images of my dating profile / chat screenshots / personal photos below. Now review them as ordered.',
						},
						...imageFileNamesArray.map((fileName) => {
							return {
								type: 'image_url',
								image_url: {
									url: process.env.AWS_S3_FILE_URL_PREFIX + fileName,
								},
							};
						}),
					],
				},
			],
			max_tokens: 700,
		});

		if (
			completion &&
			completion.choices[0] &&
			completion.choices[0].message &&
			completion.choices[0].message.content &&
			completion.choices[0].message.content
		) {
			const response = generateResponse(
				false,
				'AI response generated',
				JSON.stringify(completion.choices[0].message.content),
				'AI_RESPONSE_GENERATED',
				200
			);

			return response;
		}

		throw new Error('No message generated by openAI');
	} catch (err) {
		logError(
			'ERROR_GENERATING_AI_RESPONSE',
			err,
			'ERROR_GENERATING_AI_RESPONSE',
			{ imageFileNamesArray }
		);

		throw err;
	}
};

module.exports = { generateAIResponse };
